name: clean_app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.0
  get_it: ^7.2.0
  injectable: ^2.3.2
  auto_route: ^7.8.4
  equatable: ^2.0.5
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.2
  freezed: ^2.3.2
  dio: ^5.2.1
  json_annotation: ^4.8.0
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.4.1
  shimmer: ^3.0.0
  dartz: ^0.10.1
  retrofit: ^4.4.1
  lottie: ^2.7.0
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  icons_launcher: ^3.0.0
  firebase_core: ^3.6.0
  retrofit_generator: ^8.2.1
  rflutter_alert: ^2.0.7
  material_symbols_icons: ^4.2785.1
  firebase_auth: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  injectable_generator: ^2.1.4
  build_runner: ^2.4.6
  auto_route_generator: ^7.2.0
  json_serializable: ^6.1.4

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

